fb/ads/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.index, name='index'),
    # file update
    path('update_from_csv/', views.UpdateFbGroupFromCsv.as_view(), name='update-from-csv'),
    path('update_from_zip/', views.UpdateFbGroupFromZip.as_view(), name='update-from-zip'),
    path('update_from_txt/', views.UpdateFbGroupFromTxt.as_view(), name='update-from-txt'),

    path('groups_update/',  views.FbGroupUpdateOrCreateView.as_view(), name='group-update-list'),
    path('groups_stat/', views.groups_stat, name='groups_stat'),
    path('mark_mail_services/', views.mark_mail_services, name='mark_mail_services'),
    path('download_page/', views.download_page, name='download_page'),
    path('parse_stat_page/', views.parse_stat_page, name='parse_stat_page'),
    path('load_actual_mails/', views.load_actual_mails, name='load_actual_mails'),
    path('sleep_10/', views.sleep_10, )
]

fb/fb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='ads/main_page.html'), name='main-page'),
    path('ads/', include('ads.urls'),),
    path('fb_templates/', include('fb_templates.urls'), ),
    path('countries/', include('countries.urls'), ),
    path('remote_pc/', include('remote_pc.urls')),
]

# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

fb/ads/forms.py
import re
from django import forms
from django.db.models.functions import Concat
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from countries.models import Country
from remote_pc.models import DS


class FbLibCsvForm(forms.Form):
    csv_file = forms.FileField(
        validators=[FileExtensionValidator(allowed_extensions=['csv']),],
        widget=forms.FileInput(
            attrs={'class': "form-control"})
    )



class FbLibZipForm(forms.Form):
    FB_ADS_LIB_TYPE = 'fb_ads_lib_zip'
    FB_7_DAYS_TYPE = '7_days'
    CSV_FILES_TYPES = (
        (FB_7_DAYS_TYPE, 'Country stat'),
        (FB_ADS_LIB_TYPE, 'FaceBook Ads Library keys'),
    )
    zip_file_type = forms.ChoiceField(
        widget=forms.Select(
            attrs={'class': "form-select"},
        ),
        choices=CSV_FILES_TYPES,
    )
    zip_files = forms.FileField(
        validators=[FileExtensionValidator(allowed_extensions=['zip']),],
        widget=forms.FileInput(
            attrs={'class': "form-control"})
    )
    add_low_spend = forms.BooleanField(required=False,)


class TxtFileForm(forms.Form):
    """
    Загруска групп из txt файла
    """
    txt_files = forms.FileField(
        validators=[FileExtensionValidator(allowed_extensions=['txt']), ],
        widget=forms.FileInput(
            attrs={'class': "form-control"})
    )
    add_in_stat = forms.BooleanField(required=False)

    def clean(self):
        """При созранении` статистики должны быть указана страна в имени файла"""
        cleaned_data = super().clean()
        if cleaned_data['add_in_stat']:
            not_match_file_names = []
            loaded_countries = set()
            loaded_remote_pc = set()
            for file in self.files.getlist("txt_files"):
                try:
                    ds_name, country, other = file.name.split('_')
                    loaded_countries.add(country.lower())
                    loaded_remote_pc.add(ds_name.upper())
                except ValueError:
                    not_match_file_names.append( file.name)
            if not_match_file_names:
                raise ValidationError(
                    [ValidationError(_(f'Incorrect file name: {file_name}'), code='error') for file_name in not_match_file_names]
                )

            countries_in_db = Country.objects.filter(pk__in=loaded_countries).values('pk')
            if len(countries_in_db) != len(loaded_countries):
                if_bd_exists_codes = set([country['pk'] for country in countries_in_db])
                incorrect_codes = loaded_countries - if_bd_exists_codes
                raise ValidationError(
                    [ValidationError(_(f'Incorrect country iso code in file name: {incorrecr}!')) for incorrecr in incorrect_codes]
                )

            remote_pc_in_db = DS.objects.annotate(name_db=Concat('prefix', 'number')).filter(name_db__in=loaded_remote_pc).values('name_db')
            if len(remote_pc_in_db) != len(loaded_remote_pc):
                pc_db_exists_names = set([pc['name_db'] for pc in remote_pc_in_db])
                incorrect_pc_names = loaded_remote_pc - pc_db_exists_names
                raise ValidationError(
                    [ValidationError(_(f'Incorrect DS name: {incorrecr}!')) for incorrecr in
                     incorrect_pc_names]
                )
        return cleaned_data

fb/ads/views.py
from rest_framework.views import APIView
from datetime import datetime
from django.shortcuts import render, redirect
from .serializers import FbGroupCreateSerializer
from rest_framework.response import Response
from .forms import FbLibCsvForm, FbLibZipForm, TxtFileForm
from .fb_adlib_csv_reader import FbLibStatCsvReader, FbLibStatZipReader, Fb7DaysZipReader, TxtFileReader
from .models import FbGroup
from remote_pc.models import DS, DSDailyStat
from django.views import View
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import ThreadCounter
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db.models import Count


def index(request):
    return render(request, 'ads/index.html')


class FbGroupUpdateOrCreateView(APIView):

    def post(self, request):
        groups_items = request.data['group_urls']
        print(groups_items)
        invalid_data = []
        invalid_count = 0
        total = len(groups_items)
        new = 0
        for item in groups_items:
            serializer = FbGroupCreateSerializer(data=item)
            if serializer.is_valid():
                group, created = serializer.save()
                if created:
                    new += 1
            else:
                invalid_count += 1
                invalid_data.append(item)
        response = {
            'invalid_data': invalid_data,
            'invalid_count': invalid_count,
            'total': total,
            'new': new,
        }
        return Response(response)


class UpdateFbGroupFromCsv(View):
    """Обновить БД фб групп из csv"""
    template_name = 'ads/fb_ads_load_csv.html'

    def get(self, request):
        form = FbLibCsvForm()
        content = {
            'form': form,
        }
        return render(request, self.template_name, context=content)

    def post(self, request):
        form = FbLibCsvForm(request.POST, request.FILES)
        if form.is_valid():
            start_groups_count = FbGroup.objects.count()
            files = request.FILES.getlist('csv_file')
            readers_n_results = []
            for file in files:
                fb_lib_file_reader = FbLibStatCsvReader(file.temporary_file_path(), file_name=file.name)
                fb_lib_file_reader.read()
                update_result = FbGroup.update_db_by_group_ids(fb_lib_file_reader)
                readers_n_results.append([fb_lib_file_reader,update_result])
            content = {
                'form': FbLibCsvForm(),
                'readers_n_results': readers_n_results,
                'total_result': None,
                'new_groups_created': FbGroup.objects.count() - start_groups_count,
            }
            return render(request, self.template_name, context=content)
        else:
            content = {
                'form': form,
            }
            return render(request, self.template_name, context=content)

    def read_one_csv_file(self):

        pass

    def read_few_csv_files(self):
        pass


class UpdateFbGroupFromZip(View):
    """Обновить БД фб групп из zip"""
    template_name = 'ads/zip_load/index.html'


    def get(self, request):
        form = FbLibZipForm()
        content = {
            'form': form,
        }
        return render(request, self.template_name, context=content)

    def post(self, request):
        form = FbLibZipForm(request.POST, request.FILES)
        if form.is_valid():
            print('VALID')
            csv_file_type = form.cleaned_data['zip_file_type']
            if csv_file_type == FbLibZipForm.FB_ADS_LIB_TYPE:
                reader_class = FbLibStatZipReader
            else:
                reader_class = Fb7DaysZipReader
            start_groups_count = FbGroup.objects.count()
            readers_n_results = []
            files = request.FILES.getlist('zip_files')
            for file in files:
                if isinstance(file, InMemoryUploadedFile):
                    reader = reader_class(file, file_name=file.name, add_low_spend=form.cleaned_data['add_low_spend'])
                else:
                    reader = reader_class(file.temporary_file_path(), file_name=file.name, add_low_spend=form.cleaned_data['add_low_spend'])
                reader.read()
                update_result = FbGroup.update_db_by_group_ids(reader)
                readers_n_results.append([reader,update_result])
            content = {
                'form': FbLibZipForm(),
                'readers_n_results': readers_n_results,
                'total_result': None,  # TODO remove??
                'new_groups_created': FbGroup.objects.count() - start_groups_count,
            }
            return render(request, self.template_name, context=content)
        else:
            content = {
                'form': form,
            }
            return render(request, self.template_name, context=content)


class UpdateFbGroupFromTxt(View):
    """Обновить БД фб групп из txt"""

    template_name = 'ads/txt_load/index.html'

    def get(self, request):
        form = TxtFileForm()
        content = {
            'form': form,
        }
        return render(request, self.template_name, content)

    def post(self, request):
        print(request.POST)
        form = TxtFileForm(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES.getlist('txt_files')
            reader_class = TxtFileReader
            start_groups_count = FbGroup.objects.count()
            readers_n_results = []
            readers = []
            for file in files:
                if isinstance(file, InMemoryUploadedFile):
                    reader = reader_class(file, file_name=file.name,is_big=False)
                else:
                    reader = reader_class(file.temporary_file_path(),is_big=True, file_name=file.name,)
                    # return HttpResponse('temporary')
                reader.read()
                FbGroup.update_db_by_group_ids(reader)
                # readers_n_results.append([reader,update_result])
                readers.append(reader)
            if form.cleaned_data['add_in_stat']:
                print(readers)
                for reader in readers:
                    updated_data = {
                        'new':reader.new,
                        'updated': reader.updated,
                        'unique': reader.unique,
                        'total': reader.total,
                    }
                    DSDailyStat.add_parse_stat(
                        ds_name=reader.ds_name,
                        country_code=reader.country_code,
                        data=updated_data,
                    )

            content = {
                'form': TxtFileForm(),
                'readers': readers,
                'total_result': None, # TODO remove??
                'new_groups_created': FbGroup.objects.count() - start_groups_count,
            }
            return render(request, self.template_name, context=content)

        else:
            print(form.errors)
            content = {
                'form': form,
            }
            return render(request, self.template_name, context=content)

def groups_stat(request):
    content = {
        'with_mail_count': FbGroup.full_objects.count(),
        'no_mail_count': FbGroup.collected_no_mail_objects.count(),
        'no_data_count': FbGroup.collected_no_data_objects.count(),
        'login_form_count': FbGroup.collected_objects.filter(name='FaceBook').count(),
        'mails_service_stat': FbGroup.full_objects.values('email_service').annotate(count=Count('*')).order_by('email_service'),
        'daily_stat': FbGroup.daily_stat_new_groups(),
        'used_stat': FbGroup.used_stat(),
    }
    return render(request, 'ads/groups_stat.html', content)

def download_page(request):
    groups_updates_border_date = datetime.strptime(FbGroup.UPDATE_BORDER_DATE, '%Y-%m-%d').date()
    content = {
        'used_stat': FbGroup.used_stat(use_border_date=True),
        'groups_updates_border_date': groups_updates_border_date,
        'not_marked_mail_service_objects_exists': FbGroup.not_marked_mail_service_objects.count(),
    }
    return render(request, 'ads/download_page.html', content)

def parse_stat_page(request):
    content = {
        'not_collected_count': FbGroup.not_collected_objects.count(),
        'error_req_count': FbGroup.error_req_objects.count(),
        'in_pars_task': FbGroup.objects.filter(is_in_pars_task=True).count()
    }
    return render(request, 'ads/parse_stat_page.html', content)

def mark_mail_services(request):
    FbGroup.mark_mail_services()
    print('mark_ignored_domain_zones')
    FbGroup.mark_ignored_domain_zones()
    return redirect('ads:index')


def load_actual_mails(request):
    path = FbGroup.create_file()
    with open(path, 'rb') as fh:
        response = HttpResponse(fh.read(), content_type="text/csv")
        return response

@csrf_exempt
def sleep_10(request):
    try:
        name = request.POST['name']
        model, created = ThreadCounter.objects.get_or_create(name=name)
        model.count += 1
        model.save()
        return HttpResponse(f'{model} {model.count}')
    except Exception as error:
        return HttpResponse(str(error))

fb/ads/templates/ads/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {%block title%}
        FbAdslib Parser
        {%endblock%}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'ads/css/flag-icon.min.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

      <!--ICONS-->
  <script src="https://kit.fontawesome.com/da43c2ea11.js" crossorigin="anonymous"></script>
</head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<style>
    h1{
        color: white;
        padding: 10px 0;
        text-align: center;
        width: 100%;
    }
    .header{
        background-color: rgb(58 108 224);
        display: flex;
        align-items: center;
        margin-bottom: 20px;
    }
    .header #home-logo{
        font-size: 30px;
        color: white;
        margin: 20px;
        cursor: pointer;
    }
    .header #home-logo:hover{
        scale: 1.1;
        transition: all 0.5s ease-out;
    }
</style>
<body>
    <div class="header">
        <a href="{%url 'main-page'%}"><i id="home-logo" class="fa-solid fa-house"></i></a>
        <h1>
            {%block head_text%}
            {%endblock%}
        </h1>
    </div>

{%block content%}
{%endblock%}
</body>
</html>

fb/ads/templates/ads/download_page.html
{%extends 'ads/base.html'%}

{%block head_text%}
Скачать данные
{%endblock%}
{%block content%}
<style>
    .alert{
        display: flex;
        flex-wrap: wrap;
        gap: 30px;
        align-items: center;
    }
</style>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

{%if not_marked_mail_service_objects_exists%}
<div class="container">
<div class="alert alert-warning" role="alert">
    Есть непромаркированые емейл сервисы! ({{not_marked_mail_service_objects_exists}})      
    <a class="btn btn-warning" role="button" href="{%url 'ads:mark_mail_services'%}">Определить</a> 
</div>
</div>
{%endif%}
<div class="container">
    <div class="row">
        <div class="col">
            <canvas id="UsedMails"></canvas>
        </div>
        <div class="col">
            <h4>Дата отсчета обновлено: {{groups_updates_border_date}}</h4>
            <form>
                <div class="mb-3">
                  <label for="exampleInputEmail1" class="form-label">Email address</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                  <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1">
                </div>
                <div class="mb-3 form-check">
                  <input type="checkbox" class="form-check-input" id="exampleCheck1">
                  <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
        </div>
    </div>
</div>
<script>
    const UsedStat = document.getElementById('UsedMails');
    const UsedStatData = {
        labels: [
            //!!! {%for item in used_stat%}
            '{{item.used_count}}: {{item.count}}',
            // {%endfor%}
        ],
        datasets: [{
            label: 'My First Dataset',
            data: [
                //!!! {%for item in used_stat%}
                '{{item.count}}', 
                // {%endfor%}
            ],
            backgroundColor: [
            '#c2c2c2',
                '#59B763',
                '#ffd963',
                '#3082F1',
                '#ff6363',
                '#8963ff',
                '#ff6363',
                '#30cf7d',
                '#30cfc5',
                '#3046cf',
                '#eb9e0f',
            ],
            hoverOffset: 4
        }]
    };

    new Chart(UsedStat, {
        type: 'doughnut',
        data: UsedStatData,
        options: {
            plugins: {
                legend: {
                    position: 'left',
                    align: 'center'
                },
                title: {
                    display: true,
                    text: 'Статистика по использованым',
                }
            }
        }
    });
</script>
{%endblock%}

fb/ads/templates/ads/fb_ads_load_csv.html
{%extends 'ads/base.html'%}

{%block head_text%}
Обновить группы из CSV файла FbAdsLibrary
{%endblock%}
{%block content%}
<style>
    .wrapper{
        
    }
    .wrapper.center{
        display: flex;
        justify-content: center;
    }
    form{
        margin: 20px 0;
    }
    form button{
        margin-top: 15px;
        width: 100%;
        text-align: center;
    }
    form{
        max-width: 700px;
    }
    table{
        max-width: 400px;
    }

</style>
<div class="container">
    <div class="wrapper center">
        <form class="form" method="POST" enctype="multipart/form-data" >

            {%csrf_token%}
            <label for="formFileMultiple" class="form-label">Выберете csv файты для загрузки</label>
            {{ form.csv_file.errors }}
            <input class="form-control" name="csv_file" type="file" id="formFileMultiple" multiple required>
            <button class="btn btn-primary" type="submit">
                <div class="spinner-grow spinner-grow-sm" role="status" style="display: none;">
                    <span class="visually-hidden">Loading...</span>
                  </div>
                <span>Загузить</span>
            </button>
        </form>
    </div>
</div>
<div class="container">
    {%if readers_n_results%}
    <div class="wrapper center">
        <h4>Файлов обработано: {{readers_n_results|length}}, Создано новых групп: {{new_groups_created}}</h4>
    </div>
    {%for reader, update_result in readers_n_results%}
    <div class="wrapper center">
            <table class="table">
                <thead class="table-primary">
                <tr>
                    <td colspan="2">Файл {{reader.file_name}}</td>
                </tr>

                </thead>
                <tbody>
                <tr>
                    <td>Групп в файле</td>
                    <td>{{reader.total}}</td>
                </tr>
                <tr>
                    <td>Уникальных</td>
                    <td>{{reader|length}}</td>
                </tr>
                </tbody>
            </table>
            <table class="table">
                <thead class="table-primary">
                <tr>
                    <td colspan="2">БД</td>
                </tr>

                </thead>
                <tbody>
                <tr>
                    <td>Новых</td>
                    <td> {{update_result.new}}</td>
                </tr>
                <tr>
                    <td>Обновлено</td>
                    <td>{{update_result.updated}}</td>
                </tr>
                </tbody>
            </table>    
    </div>
    {%endfor%}
    {%endif%}
    
</div>
<script>
    $('form').submit(function(){
        console.log('123')
    $('form button').attr('disabled', true)
    $('form button .spinner-grow').show()
    $('form button span').text('Загружаеться')
    })
</script>
{%endblock%}

fb/ads/templates/ads/groups_stat.html
{%extends 'ads/base.html'%}

{%block head_text%}
Статистика групп
{%endblock%}
{%block content%}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<div class="container-fluid">

    <div class="row">
        <div class="col">
            <canvas id="ColectedStat"></canvas>
        </div>
        <div class="col">
            <canvas id="mailServiceStat"></canvas>
        </div>
        <div class="col">
            <canvas id="UsedMails"></canvas>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col">
            <canvas id="newGroupsDaily"></canvas>
        </div>
    </div>
</div>


<script>
    const ColectedStat = document.getElementById('ColectedStat');
    const ColectedStatData = {
        labels: [
            'With mail: {{with_mail_count}}',
            'Title only: {{no_mail_count}}',
            'Login form: {{login_form_count}}',
            'Emtpy: {{no_data_count}}',
        ],
        datasets: [{
            label: 'My First Dataset',
            data: ['{{with_mail_count}}', '{{no_mail_count}}', '{{login_form_count}}', '{{no_data_count}}'],
            backgroundColor: [
                '#59B763',
                '#ffd963',
                '#3082F1',
                '#ff6363'
            ],
            hoverOffset: 4
        }]
    };

    new Chart(ColectedStat, {
        type: 'doughnut',
        data: ColectedStatData,
        options: {
            plugins: {
                legend: {
                    position: 'left',
                    align: 'center'
                },
                title: {
                    display: true,
                    text: 'Статистика по обработанным группам',
                }
            }
        }
    });
</script>

<script>
    const mailServiceStat = document.getElementById('mailServiceStat');
    const mailServiceStatData = {
        labels : [
            //!!! {%for item in mails_service_stat%}
            '{{item.email_service}}: {{item.count}}',
            //!!! {%endfor%}
        ],
        datasets: [{
            label: 'My First Dataset',
            data: [
            //!!! {%for item in mails_service_stat%}
            '{{item.count}}',
            //!!! {%endfor%}
            ],
            backgroundColor: [
                '#c2c2c2',
                '#59B763',
                '#ffd963',
                '#3082F1',
                '#ff6363',
                '#8963ff',
                '#ff6363',
                '#30cf7d',
                '#30cfc5',
                '#3046cf',
                '#eb9e0f',
            ],
            hoverOffset: 4
        }]
    };

    new Chart(mailServiceStat, {
        type: 'doughnut',
        data: mailServiceStatData,
        options: {
            plugins: {
                legend: {
                    position: 'left',
                    align: 'center'
                },
                title: {
                    display: true,
                    text: 'Статистика по сервисам',
                }
            }
        }
    });
</script>
<script>

    const newGroupsDaily = document.getElementById('newGroupsDaily');
    const labels = [
        // {%for item in daily_stat%}
        '{{item.date}}',
        // {%endfor%}
    ];
    const data = {
      labels: labels,
      datasets: [{
        label: 'Статистика добавления новых групп по дням',
        data: [
        // {%for item in daily_stat%}
        '{{item.count}}',
        // {%endfor%}
    ],
        borderWidth: 1
      }]
    };
    
    
    const config = {
      type: 'bar',
      data: data,
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      },
    };
    
    
    new Chart(newGroupsDaily, config)
        </script>

<script>
    const UsedStat = document.getElementById('UsedMails');
    const UsedStatData = {
        labels: [
            //!!! {%for item in used_stat%}
            '{{item.used_count}}: {{item.count}}',
            // {%endfor%}
        ],
        datasets: [{
            label: 'My First Dataset',
            data: [
                //!!! {%for item in used_stat%}
                '{{item.count}}', 
                // {%endfor%}
            ],
            backgroundColor: [
            '#c2c2c2',
                '#59B763',
                '#ffd963',
                '#3082F1',
                '#ff6363',
                '#8963ff',
                '#ff6363',
                '#30cf7d',
                '#30cfc5',
                '#3046cf',
                '#eb9e0f',
            ],
            hoverOffset: 4
        }]
    };

    new Chart(UsedStat, {
        type: 'doughnut',
        data: UsedStatData,
        options: {
            plugins: {
                legend: {
                    position: 'left',
                    align: 'center'
                },
                title: {
                    display: true,
                    text: 'Статистика по использованым',
                }
            }
        }
    });
</script>
{%endblock%}

fb/ads/templates/ads/index.html
{%extends 'ads/base.html'%}

{%block head_text%}
Main
{%endblock%}
{%block content%}
<style>
    .card i{
        font-size: 150px;
        text-align: center;
        margin: 10px 0;
        color: rgb(58 108 224);
    }
</style>
<br>
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
          <div class="card text-center">
            <a href="{%url 'ads:update-from-zip' %}">
                <i class="fa-regular fa-file-zipper"></i>
            </a>
            <div class="card-body">
              <h5 class="card-title">Zip</h5>
              <p class="card-text">Загузить группы из файла Zip</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card text-center">
            <a href="{%url 'ads:update-from-csv' %}">
                <i class="fa-solid fa-file-csv"></i>
            </a>
            <div class="card-body">
              <h5 class="card-title">CSV</h5>
              <p class="card-text">Загузить группы из файла csv</p>
            </div>
          </div>
        </div>
        <div class="col">
            <div class="card text-center">
                <a href="{%url 'ads:update-from-txt' %}">
                  <i class="fa-regular fa-file-lines"></i>
                </a>
              <div class="card-body">
                <h5 class="card-title">TXT</h5>
                <p class="card-text">Загузить группы из файла TXT</p>
              </div>
            </div>
          </div>
      </div>
</div>
<br>
<div class="container">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
      <div class="card text-center">
          <a href="{%url 'ads:groups_stat'%}">
              <i class="fa-solid fa-chart-column"></i>
          </a>
        <div class="card-body">
          <h5 class="card-title">Статистика</h5>
          <p class="card-text">Статистика по группам</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card text-center">
          <a href="{%url 'ads:download_page' %}">
            <i class="fa-solid fa-cloud-arrow-down"></i>
          </a>
        <div class="card-body">
          <h5 class="card-title">Скачать</h5>
          <p class="card-text">Скачать результаты</p>
        </div>
      </div>
    </div>
    
    <div class="col">
      <div class="card text-center">
          <a href="{%url 'ads:parse_stat_page' %}">
            <i class="fa-solid fa-magnifying-glass-location"></i>
          </a>
        <div class="card-body">
          <h5 class="card-title">Парсинг</h5>
          <p class="card-text">Парсинг данных с групп</p>
        </div>
      </div>
    </div>
  </div>
</div>

{%endblock%}

fb/ads/templates/ads/key_words.html
{%extends 'ads/base.html'%}

{%block head_text%}
Key words
{%endblock%}
{%block content%}
<style>
    input{
        margin-right: 10px;
    }
</style>
<div class="container">
    {%for key_word in key_words%}
<input type="checkbox"><a href="{{key_word.url}}" target="_blank">{{key_word}} - {{key_word.ads_count}}</a><br>
{%endfor%}
</div>
{%endblock%}