fb/fb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='ads/main_page.html'), name='main-page'),
    path('ads/', include('ads.urls'),),
    path('fb_templates/', include('fb_templates.urls'), ),
    path('countries/', include('countries.urls'), ),
    path('remote_pc/', include('remote_pc.urls')),
]

# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

fb/fb_templates/urls.py
from django.urls import path
from . import views
app_name = 'fb_templates'
urlpatterns = [
    path('', views.index, name='index'),
    path('examples/', views.email_examples, name='email_examples'),
    path('view/<int:tmp_id>/', views.view_template, name='view_template'),
]

fb/fb_templates/models.py
from django.db import models

# Create your models here.
class FbTemplate(models.Model):
    desc = models.CharField(
        max_length=255,
        blank=True
    )
    file = models.FileField(
        upload_to='fb_templates',
    )
    prev = models.URLField(
        blank=True,
    )

    @property
    def html(self):
        with open(self.file.path, encoding='utf-8') as file:
            return file.read()


class EmailExample(models.Model):
    img_url = models.URLField()

fb/fb_templates/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import FbTemplate, EmailExample


def index(request):
    content = {
        'fb_templates': FbTemplate.objects.all().order_by('-pk')
    }
    return render(request,'fb_templates/index.html', content)


def view_template(request, tmp_id):
    temp = FbTemplate.objects.get(pk=tmp_id)
    return HttpResponse(temp.html)


def email_examples(request):
    emails_images = EmailExample.objects.all()
    content = {
        'emails_img': emails_images
    }
    return render(request, 'fb_templates/emails_examples.html', content)

fb/fb_templates/templates/fb_templates/index.html
{%extends 'ads/base.html'%}

{%block head_text%}
Шаблоны
{%endblock%}
{%block content%}
<div style="display: flex;justify-content: center;">
  <a href="{%url 'fb_templates:email_examples'%}" class="btn btn-light">Скрины примеров</a>
</div>
<br>
<div class="container-fluid">
    <div class="row row-cols-1 row-cols-md-5 g-5">
        {%for fb_template in fb_templates%}
        <div class="col">
          <div class="card text-center">
            {%if fb_template.prev%}
            <img src="{{fb_template.prev}}" class="card-img-top" alt="">
            {%else%}
            <img src="https://t4.ftcdn.net/jpg/04/00/24/31/360_F_400243185_BOxON3h9avMUX10RsDkt3pJ8iQx72kS3.jpg" class="card-img-top" alt="">
            {%endif%}
            <div class="card-body">
              <p class="card-text">{{fb_template.file.name}}</p>
              <a href="{%url 'fb_templates:view_template' fb_template.pk %}" class="btn btn-secondary" target="_blank">See {{fb_template.pk}}</a>
            </div>
          </div>
        </div>
        {%endfor%}
      </div>
</div>
{%endblock%}