fb/countries/urls.py
from django.urls import path
from . import views
app_name = 'countries'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:pk>/', views.country, name='country'),
    path('fb_adslib/show_key', views.ShowLibrary.as_view(), name='fb_adslib_show'),
    path('vocabulary/<str:pk>/update', views.CountryLanguageUpdateView.as_view(),name='vocabulary-update'),

    path('country-comment/create/', views.CountryCommentCreateView.as_view(), name='country-comment-create'),
    path('country-comment/<int:pk>/delete/', views.CountryCommentDeleteView.as_view(), name='country-comment-create'),
]

fb/fb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='ads/main_page.html'), name='main-page'),
    path('ads/', include('ads.urls'),),
    path('fb_templates/', include('fb_templates.urls'), ),
    path('countries/', include('countries.urls'), ),
    path('remote_pc/', include('remote_pc.urls')),
]

# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

fb/countries/models.py
from django.db.models import Sum, Avg, Count, Max, F, FloatField
from django.db.models.functions import Round, Cast
from django.apps import apps
from django.db import models
from django.core.validators import RegexValidator

counter = 0


def get_pk():
    global counter
    counter += 1
    return counter


class WorldPart(models.Model):
    name = models.CharField(max_length=50)
    ru_name = models.CharField(max_length=50)
    color = models.CharField(max_length=10, blank=True)

    def __str__(self):
        return self.ru_name


class Country(models.Model):
    iso = models.CharField(
        max_length=2,
        verbose_name='Код страны ISO',
        unique=True,
        primary_key=True,
    )
    iso3 = models.CharField(
        max_length=3,
        verbose_name='ISO 3',
        unique=True,
        blank=True,
        null=True,
    )
    ru_full_name = models.CharField(
        max_length=60,
        verbose_name='Русское название',
        blank=True,
        unique=True,
    )
    phone = models.CharField(
        max_length=15,
        verbose_name='Валидный номер',
        blank=True,
    )
    phone_code = models.CharField(
        max_length=15,
        verbose_name='Моб код страны',
        blank=True,
    )
    words = models.JSONField(
        default={"words": [], "templates": []},
        verbose_name='Слова под гео'
    )
    language = models.ManyToManyField(
        'Language',
        blank=True,
        through="CountryLanguage",
    )
    curr = models.ManyToManyField(
        'Currency',
        blank=True,
    )
    population = models.IntegerField(default=0)
    parse_population_conf = models.PositiveIntegerField(default=1, verbose_name='Коофициен для парса по населению')
    use_in_parse = models.BooleanField(default=False)
    world_part = models.ForeignKey(
        WorldPart,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='country'
    )

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'

    def __str__(self):
        return self.pk.upper()

    def stat(self):
        if self.ds_stat.exists():
            stat = Country.objects.filter(pk=self.pk).aggregate(total_sum=Sum('ds_stat__total'),
                                                                unique_sum=Sum('ds_stat__unique'),
                                                                new_sum=Sum('ds_stat__new'))
            stat['unique_percent'] = round(stat['unique_sum'] / stat['total_sum'] * 100)
            stat['new_percent'] = round(stat['new_sum'] / stat['unique_sum'] * 100)
            return stat

    def country_new_daily_stat(self):
        """Статистика наработки по дням"""
        stat = self.ds_stat.values('created').annotate(new=Sum('new'), total=Sum('total')).annotate(
            avg=Cast(Round(F('new') / F('total') * 100, 1), FloatField())).order_by('created')
        return stat


class CountryComment(models.Model):
    TYPES = [
        ('danger', 'Danger'),
        ('primary', 'Primary'),
        ('success', 'Success'),
        ('warning', 'Warning'),
    ]
    country = models.ForeignKey(
        to=Country,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    type = models.CharField(max_length=10, choices=TYPES, )
    created = models.DateField(auto_now_add=True)


class Language(models.Model):
    iso = models.CharField(
        max_length=2,
        verbose_name='Код iso языка',
        primary_key=True)
    russian_name = models.CharField(
        max_length=25,
        verbose_name='Русское название',
        blank=True
    )
    discount_text = models.CharField(max_length=250, blank=True)
    has_vocabulary = models.BooleanField(default=False)

    class Meta:
        ordering = ['iso']

    def __str__(self):
        return f'{self.russian_name}({self.iso.upper()})'


class Currency(models.Model):
    name = models.CharField(
        max_length=60,
        verbose_name='Название валюты'
    )
    iso = models.CharField(
        max_length=3,
        primary_key=True,
        verbose_name='Код валюты',
        unique=True)
    iso_3366 = models.CharField(
        max_length=3,
        verbose_name='ISO 3166-1',
        unique=True,
        blank=True,
        null=True
    )
    kma_code = models.CharField(
        max_length=5,
        verbose_name='Валюта в кма',
        blank=True,
        default=''
    )

    def __str__(self):
        return f'{self.name}({self.iso.upper()})'


class KeyWord(models.Model):
    number_in_dict = models.IntegerField()
    word = models.CharField(
        max_length=255,
        # validators=[RegexValidator(regex='([A-Za-z]){1,30}', message='Incorrect eng key word')]
    )
    language = models.ForeignKey(
        to=Language,
        on_delete=models.PROTECT,
        related_name='keywords',
    )

    class Meta:
        ordering = ['number_in_dict', ]
        # unique_together = ['word', 'language']

    def __str__(self):
        return f'{self.language_id} {self.number_in_dict}: {self.word}'


class CountryLanguage(models.Model):
    """Языковой словарь страны"""
    POP_KEYSDEEP_COOF = [
        # population, keys_deep
        [0, 200],
        [5, 300],
        [10, 500],
        [20, 1000],
        [40, 2000],
        [80, 2500],
        [120, 3500],
        [160, 4000],
        [200, 5000],
        [250, 7000],
        [300, 8000],
    ]

    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    country = models.ForeignKey(Country, on_delete=models.CASCADE,
                                related_name='vocabulary',
                                )
    keys_deep = models.PositiveIntegerField(blank=True, null=True, )
    weight = models.PositiveIntegerField(blank=True, default=1, verbose_name='Весовой кооф языковой группы')

    class Meta:
        verbose_name = 'Словарь по стране'
        verbose_name_plural = 'Словари по странам'
        unique_together = ['country', 'language']

    def __repr__(self):
        return f'CountryLang: {self.country_id}-{self.language_id}'

    def __str__(self):
        return f'{self.country_id}-{self.language_id}'.upper()

    @staticmethod
    def get_deep_by_pop(population):
        deep = None
        if not population:
            return deep
        for pop, keys_deep in CountryLanguage.POP_KEYSDEEP_COOF:
            if population >= pop:
                deep = keys_deep
        return deep

    def set_keys_deep(self):
        deep = CountryLanguage.get_deep_by_pop(self.speakers_population)
        self.keys_deep = deep
        self.save()

    @property
    def percent_of_lang(self) -> float:
        country = self.country
        vocs = country.vocabulary.all()
        total_weight = sum([voc.weight for voc in vocs])
        try:
            return round(self.weight / total_weight, 2)
        except ZeroDivisionError:
            return 0

    @property
    def speakers_population(self):
        return round(self.country.parse_population_conf * self.percent_of_lang)

fb/countries/forms.py
from django.forms import ModelForm
from .models import CountryLanguage


class CountryLanguageForm(ModelForm):

    class Meta:
        fields = ['keys_deep', 'weight']

fb/countries/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .models import Country, CountryLanguage, Language, KeyWord, CountryComment, WorldPart
from .forms import CountryLanguageForm
from django.views import View
from django.views.generic import DetailView, UpdateView, DeleteView
from django.urls import reverse
from django.views.generic import CreateView
from django.db.models import Prefetch

def index(request):
    countries = Country.objects.filter(use_in_parse=True).order_by('-population')
    world_parts = WorldPart.objects.prefetch_related(Prefetch(
       'country', queryset=countries
    ))

    content = {
        'world_parts': world_parts,
    }
    return render(request, 'countries/index.html', content)

def country(request, pk):
    country = Country.objects.get(pk=pk)
    country_stat = country.stat()
    content = {
        'country': country,
        'country_stat': country_stat,
        'country_new_daily_stat': country.country_new_daily_stat(),
    }
    return render(request, 'countries/country.html', content)


class ShowLibrary(View):

    def post(self, request):
        country = Country.objects.get(pk=request.POST['country'])
        language = Language.objects.get(pk=request.POST['language'])
        number_in_dict = request.POST['number_in_dict']
        keyword = KeyWord.objects.get(language=language, number_in_dict=number_in_dict)
        adslib_url = f'https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country={country.pk.upper()}&q={keyword.word}&publisher_platforms[0]=facebook&sort_data[direction]=desc&sort_data[mode]=relevancy_monthly_grouped&start_date[min]=2023-12-17&start_date[max]=&search_type=keyword_unordered&media_type=all'
        return HttpResponseRedirect(adslib_url)


class CountryLanguageUpdateView(UpdateView):

    queryset = CountryLanguage.objects.all()
    template_name = 'countries/test.html'
    fields = ['keys_deep', 'weight']

    def get_success_url(self):
        obj = self.get_object()
        return reverse("countries:country", kwargs={"pk": obj.country_id})


class CountryCommentCreateView(CreateView):
    queryset = CountryComment.objects.all()
    fields = ['text', 'country', 'type']

    def get_success_url(self):
        country = Country.objects.get(pk=self.request.POST['country'])
        return reverse("countries:country", kwargs={"pk":country.pk})

class CountryCommentDeleteView(DeleteView):
    queryset = CountryComment.objects.all()

    def get_success_url(self):
        obj = self.get_object()
        country = Country.objects.get(pk=obj.country)
        return reverse("countries:country", kwargs={"pk":country.pk})

fb/countries/templates/countries/country.html
{% extends 'ads/base.html' %}
{% load static %}
{% load country_filters%}
{%block title%}
        {{country}} - {{country.ru_full_name}}
{%endblock%}
{% block content %}
<!-- Resources -->
<script src="https://cdn.amcharts.com/lib/5/index.js"></script>
<script src="https://cdn.amcharts.com/lib/5/percent.js"></script>
<script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<style>

</style>
<style>
    .country-info-block{
        margin-bottom: 20px;
        display: flex;
        flex-wrap: wrap;
        gap: 80px;
        margin-bottom: 120px;
    }
    .country-name{
        display: flex;
        align-items: center;
    }
    .flag-icon{
        margin-right: 30px;
        width: 100px;
        height: 100px;
    }
    .view-key-form{
        display: flex;
        align-items: center;
        flex-wrap:wrap;
        gap: 10px;
        padding: 10px;
    }
    .view-key-form input{
        width: 150px;
    }
    .voc-block{
        margin-top: 30px;
    }
    .voc-form{
      display: flex;
      justify-content: flex-start;
    }
    .voc-form .btn-wrap{
      display: flex;
      align-items: center;
      padding: 20px;
    }
    .voc-form button{
        margin-top: 10px;
    }
    .voc-form input{
        max-width: 250px;
    }
    .alert{
        display: flex;
        justify-content: space-between;
    }
    .alert i{
        margin-left: 8px;
        cursor: pointer;
        transition: 0.3s;
    }
    .alert i:hover{
        color: rgb(99, 11, 11);
    }
    .comment-block{
        margin: 20px 0;
    }

</style>
<style>

    .pie{
        width: 200px;
        height: 200px;
    }
    .pie label{
        text-align: center;
        width: 100%;
        font-weight: 800;
        margin-bottom:20px;
    }
    </style>
<!-- <div class="container-fluid country-info-block">
   <div>
    <h2 class="country-name"><span class="flag-icon flag-icon-{{country.pk}}"></span>{{country.ru_full_name}}</h2>
    <p>Население: {{country.population|population_short}}</p>
    <p>ВВП нанос:</p>
   </div>
   {%if country.stat%}
    <div class="pie" id="uniqie_percent">
        <label for=""></label>
    </div>
    <div class="pie" id="new_percent">
        <label for=""></label>
    </div>
    <div >
      <canvas  style="width: 100%;" id="country_new_daily_stat"></canvas>
    </div>
    
    {%else%}
    <h5>Нет собраной статистики</h5>
   {%endif%}
</div> -->
<div class="container-fluid">
  <div class="row">
    <div class="col-2">
      <span class="flag-icon flag-icon-{{country.pk}}"></span>
      <h2 class="country-name">{{country.ru_full_name}}</h2>
      <p>Население: {{country.population|population_short}}</p>
      <p>Парс кооф: {{country.parse_population_conf}}</p>
    </div>

    {%if country.stat%}
    <div class="col-2">
      <div class="pie" id="uniqie_percent">
        <label for=""></label>
    </div>
    </div>
    <div class="col-2">
      <div class="pie" id="new_percent">
        <label for=""></label>
    </div>
    </div>
    <div class="col-6">
      <canvas   id="country_new_daily_stat"></canvas>
    </div>
    {%else%}
    <div class="col-10">
      <h5>Нет собраной статистики</h5>
    </div>
   {%endif%}
  </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h5 >Доступные языки  </h5>
            {%for voc in country.vocabulary.all%}  
            <div class="container voc-block">
            {%if voc.language.has_vocabulary%}
            <h6>{{voc.language}}</h6>
            <form class="voc-form" action="{%url 'countries:vocabulary-update' voc.pk%}" method="POST">
                {%csrf_token%}
                <div>
                  <div>
                    <label for="" class="form-label">Грубина ключей</label>
                      <input type="text" value="{{voc.keys_deep|default_if_none:''}}" name="keys_deep" required class="form-control" placeholder="Задайте шлубину ключей">
                  </div>
                  <div>
                    <label for="" class="form-label">Задайте кооф языковой группы</label>
                    <input type="text" class="form-control" value="{{voc.weight}}" name="weight" required>
                  </div>
                </div>
                    <div class="btn-wrap">
                      <button type="submit" class="btn btn-primary">Обновить {{voc}}</button>
                    </div>
            </form>
            {%else%}
            <h6>{{voc.language}}: Не словаря</h6>
            {%endif%}
        </div>
            {%endfor%}
        </div>
        <div class="col">
            <h5 >Коментарии к гео </h5>
            <button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                Добавить
              </button>
            
            <div class="collapse" id="collapseExample">
                <form action="{% url 'countries:country-comment-create' %}" method="POST">
                    {%csrf_token%}
                    <select class="form-select" aria-label="Default select example" name="type">
                        <option value="danger">Danger</option>
                        <option value="primary" selected>Primary</option>
                        <option value="success">Success</option>
                        <option value="warning">Warning</option>
                      </select>
                    <input class="form-control" type="hidden" name="country" value="{{country.pk}}">
                    <textarea class="form-control" name="text" id="" cols="30" rows="3"></textarea>
                    <button type="submit" class="btn btn-primary">Создать</button>
                </form>
              </div>
            
            <div class="comment-block">
                {%for comment in country.comments.all%}
            <div class="alert alert-{{comment.type}}" role="alert" id="comment-{{comment.pk}}">
                <div class="text">
                    {{comment.text}}
                </div>
                 <div>
                    {{comment.created}}
                    <i class="fa-solid fa-trash"></i>
                </div>
              </div>
              {%empty%}
              <p>Нет коментариев</p>
             {%endfor%}   
            </div>            
        </div>
        <div class="col">
            <h5 >Обзор Facebook Ads Library по {{country.ru_full_name}}</h5>
            {%for voc in country.vocabulary.all%}
            <form class="view-key-form"action="{%url 'countries:fb_adslib_show' %}" target="_blank" method="POST">
                <label for="" class="form-label">{{voc.language}}</label>
                {%csrf_token%}
                <input name="country" value="{{country.pk}}" type="hidden">
                <input name="language" value="{{voc.language.pk}}" type="hidden">
                <input class="form-control" name="number_in_dict" type="number" placeholder="Введите номер ключа" required min="1" max="20000">
                <button type="submit" class="btn btn-secondary">Показать ключ</button>
            </form>
            
            {%endfor%}
        </div>
    </div>
    
    
</div>

  <!-- Remove comment Modal -->
  <div class="modal fade" id="deleteCommentModal" tabindex="-1" aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteCommentModalLabel">Удалить коментарий?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <form action="" method="POST">
            {%csrf_token%}
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
          
        </div>
      </div>
    </div>
  </div>
  
<script>
    var modalBlock = document.getElementById('deleteCommentModal')
    var deleteModal = new bootstrap.Modal(modalBlock)
    var modalText = modalBlock.querySelector('.modal-body')
    var modalForm = modalBlock.querySelector('form')
    var removeCommentButtons = document.querySelectorAll('.alert i')
    removeCommentButtons.forEach(function(elem){
        console.log(elem)
        elem.addEventListener('click', showDeleteCommentModal)
    })

    function showDeleteCommentModal(event){
        var target = event.target
        var alertBlock = target.closest(".alert")
        var commentId = alertBlock.id.replace('comment-','')
        modalText.innerHTML = alertBlock.querySelector('.text').innerText
        var deleteUrl = `/countries/country-comment/${commentId}/delete/`
        modalForm.action = deleteUrl
        deleteModal.show()
    }
</script>

<!-- Unique code -->
<script>
    function createChart(label_text,id, data, center_text){
        var elem = document.getElementById(id)
        elem.querySelector('label').innerText = label_text
        ///
        am5.ready(function() {
    var chartData = {};
    var root = am5.Root.new(id);
    
    root.setThemes([
      am5themes_Animated.new(root)
    ]);
    var chart = root.container.children.push(am5percent.PieChart.new(root, {
      innerRadius: 100,
      layout: root.verticalLayout
    }));
    var series = chart.series.push(am5percent.PieSeries.new(root, {
      valueField: "size",
      categoryField: "sector"
    }));
    series.data.setAll(data);
    series.appear(1000, 100);
    series.labels.template.set("visible", false);
    series.ticks.template.set("visible", false);
    
    // Add label
    var label = root.tooltipContainer.children.push(am5.Label.new(root, {
      x: am5.p50,
      y: am5.p50,
      centerX: am5.p50,
      centerY: am5.p50,
      fill: am5.color(0x000000),
      fontSize: 50
    }));
    

    label.set("text", center_text);
    
    });
        ///
    }

    createChart('Уникальных','uniqie_percent',
    [{ sector: "Уникальных", size: '{{country_stat.unique_sum}}'},
    { sector: "Всего собрано", size: '{{country_stat.total_sum}}' -  '{{country_stat.unique_sum}}'},
    ]
    , '{{country_stat.unique_percent}}%')

    createChart('Новых','new_percent',
    [{ sector: "Новых", size: '{{country_stat.new_sum}}'},
    { sector: "Уникальных", size: '{{country_stat.unique_sum}}' - '{{country_stat.new_sum}}'},
    ]
    , '{{country_stat.new_percent}}%')
    
    </script>


<script>
    //Статистика новых по стране по дням
    const country_new_daily_stat = document.getElementById('country_new_daily_stat');
    const country_new_daily_stat_labels = [
          // {%for item in country_new_daily_stat%}
          '{{item.created}} - {{item.avg}}%',
          // {%endfor%}
      ];
      const country_new_daily_stat_data = {
    labels: country_new_daily_stat_labels,
    datasets: [
   
      {
        label: 'Новых групп',
        data: [
             // {%for item in country_new_daily_stat%}
          '{{item.new}}',
          // {%endfor%}
        ],
  
      },
      {
        label: 'Всего карт',
        data: [
             // {%for item in country_new_daily_stat%}
          '{{item.total}}' - '{{item.new}}',
          // {%endfor%}
        ],
  
      },
    ]
  };
      
      
      const country_new_daily_stat_config = {
        type: 'bar',
        data: country_new_daily_stat_data,
        options: {
          scales: {
        x: {
          stacked: true,
        },
        y: {
          stacked: true
        }
      }
        },
      };
      new Chart(country_new_daily_stat, country_new_daily_stat_config)
  </script>
{%endblock%}

fb/countries/templates/countries/index.html
{% extends 'ads/base.html' %}
{% load static %}
{% load country_filters%}
{%block head_text%}
Страны для парса
{%endblock%}
{% block content %}
<style>
  .country_voc{
    margin-top: 1px;
    margin-bottom: 1px;
  }
</style>

<div class="container">
  {%for world_part in world_parts%}
  <h1 style="background-color: {{world_part.color}};">{{world_part}}</h1>
  <table class="table table table-striped">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">ISO</th>
      <th scope="col">Страна</th>
      <th scope="col">Регион</th>
      <th scope="col">Население</th>
      <th scope="col">ParseWeight</th>
      <th scope="col">Язык</th>
      <th scope="col">Админ</th>
      
    </tr>
  </thead>
  <tbody>

        {% for country in world_part.country.all %}
          <tr>
            <th scope="row"><span class="flag-icon flag-icon-{{country.pk}}"></span></th>
            <th scope="row" style="text-transform: uppercase;">
              <a target="_blank" href="{%url 'countries:country' country.pk %}">{{country.iso}}</a>
            </th>
            <td>{{country.ru_full_name}}</td>
            <td>{{country.world_part|default_if_none:"-"}}</td>
            <td>{{country.population|population_short}}</td>
            <td>
              {{country.parse_population_conf}}
            </td>
            <td>
              {%for voc in country.vocabulary.all%}
              <p class="country_voc">{{voc.language}} Deep: {{voc.keys_deep|default_if_none:"-"}} </p>
              {%endfor%}
            </td>
            <td>
              <a target="_blank" href="/admin/countries/country/{{country.pk}}/change/">Редактировать</a>
            </td>

          </tr>
  {% endfor %}

  </tbody>
</table>
{%endfor%}

</div>

{% endblock %}

fb/countries/templates/countries/test.html
update