fb/fb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='ads/main_page.html'), name='main-page'),
    path('ads/', include('ads.urls'),),
    path('fb_templates/', include('fb_templates.urls'), ),
    path('countries/', include('countries.urls'), ),
    path('remote_pc/', include('remote_pc.urls')),
]

# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

fb/remote_pc/urls.py
from django.urls import path
from . import views

app_name = 'remote_pc'
urlpatterns = [
    path('', views.index, name='index'),
    path('active/', views.active, name='active'),
    path('parse-stat', views.parse_stat, name='parse_stat'),
    path('ping-ds/<str:ds_name>/', views.ping_ds,),
]

fb/remote_pc/models.py
from django.db import models
from django.db.models.functions import Concat
from django.utils import timezone
from django.db.models import Sum, Avg, Count, Max, F, FloatField
from django.db.models.functions import Round, Cast
from datetime import timedelta
from django.core.validators import RegexValidator
from countries.models import Country
from datetime import datetime


class DS(models.Model):
    PREFIXES = (
        ('PC', 'Желеска (PC)'),
        ('D', 'Дэдик (D)')
    )
    OS = (
        ('Windows', 'Windows'),
        ('Linux', 'Linux'),
    )
    WORK = 'Работает'
    NOT_WORK = 'Не работает'
    NOT_ACTIVE = 'Не активен'
    prefix = models.CharField(max_length=5, choices=PREFIXES, )
    number = models.CharField(max_length=50, )
    full_name = models.CharField(max_length=50, blank=True)
    ip = models.GenericIPAddressField()
    login = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    core = models.PositiveIntegerField()
    ram = models.PositiveIntegerField()
    os = models.CharField(max_length=50, choices=OS)
    last_activity = models.DateTimeField(blank=True, null=True)
    use_in_pars = models.BooleanField(default=True)
    color = models.CharField(max_length=7, blank=True, )

    def __str__(self):
        return self.name()

    class Meta:
        unique_together = ['prefix', 'number']
        verbose_name = 'DS'
        verbose_name_plural = 'DS'
        ordering = ['number', 'prefix']

    def name(self):
        return f'{self.prefix}{self.number}'

    def ping(self):
        self.last_activity = timezone.now()
        self.save()

    def past(self):
        if self.last_activity:
            delta = timezone.now() - self.last_activity
            return delta
        return ''

    @staticmethod
    def last_parse_date():
        return DSDailyStat.objects.aggregate(last_date=Max('created'))['last_date']

    @property
    def status(self):
        WORK = {
            'text': DS.WORK,
            'color': 'success',
        }
        MAYBE_WORK = {
            'text': DS.WORK,
            'color': 'warning',
        }
        NOT_WORK = {
            'text': DS.NOT_WORK,
            'color': 'danger',
        }
        NOT_ACTIVE = {
            'text': DS.NOT_ACTIVE,
            'color': 'secondary',
        }
        if self.last_activity:
            delta = timezone.now() - self.last_activity
            if delta > timedelta(minutes=45):
                return NOT_ACTIVE
            elif delta > timedelta(minutes=10):
                return NOT_WORK
            elif delta > timedelta(minutes=5):
                return MAYBE_WORK
            else:
                return WORK
        return NOT_ACTIVE

    @staticmethod
    def daily_total_stat():
        return DSDailyStat.objects.values('created').annotate(total=Sum('total')).order_by('created')

    @staticmethod
    def dss_today_stat():
        last_date = DS.last_parse_date()
        stat = DSDailyStat.objects.select_related('ds').filter(created=last_date).values('ds', 'ds__number',
                                                                                         'ds__prefix',
                                                                                         'ds__color', ).annotate(
            avg=Sum('total') / Count('created', distinct=True)
        )
        return sorted(stat, key=lambda item: (item['ds__prefix'], int(item['ds__number'])))

    @staticmethod
    def dss_avg_stat():
        stat = DSDailyStat.objects.select_related('ds').values('ds', 'ds__number', 'ds__prefix',
                                                               'ds__color', ).annotate(
            avg=Sum('total') / Count('created', distinct=True)
        )
        return sorted(stat, key=lambda item: (item['ds__prefix'], int(item['ds__number'])))


class DSDailyStat(models.Model):
    ds = models.ForeignKey(DS, on_delete=models.CASCADE)
    country = models.ForeignKey(
        Country,
        on_delete=models.CASCADE,
        related_name='ds_stat',
    )
    total = models.PositiveIntegerField(default=0)
    unique = models.PositiveIntegerField(default=0)
    new = models.PositiveIntegerField(default=0)
    updated = models.PositiveIntegerField(default=0)
    created = models.DateField(auto_now_add=True)

    class Meta:
        unique_together = ['ds', 'created', 'country']

    @staticmethod
    def country_last_date_new_stat():
        """статистика новых за последний день по странам"""
        last_date = DS.last_parse_date()
        stat = (DSDailyStat.objects.filter(created=last_date).values('country_id').
                annotate(new=Sum('new'), total=Sum('total')).
                annotate(avg=Cast(Round(F('new') / F('total') * 100, 1), FloatField())
                         ))
        stat = sorted(stat, key=lambda item: item['avg'], reverse=True)  # TODO rename avg
        return {
            'date': last_date,
            'stat': stat,
        }

    @staticmethod
    def add_parse_stat(ds_name, country_code, data):
        date = datetime.now().date()
        ds = DS.objects.annotate(namedb=Concat('prefix', 'number')).get(namedb=ds_name)
        country = Country.objects.get(pk=country_code)
        ds_daily_stat_record, created = DSDailyStat.objects.get_or_create(
            created=date,
            country=country,
            ds=ds,
        )
        ds_daily_stat_record.total = ds_daily_stat_record.total + data['total']
        ds_daily_stat_record.unique = ds_daily_stat_record.unique + data['unique']
        ds_daily_stat_record.updated = ds_daily_stat_record.updated + data['updated']
        ds_daily_stat_record.new = ds_daily_stat_record.new + data['new']
        ds_daily_stat_record.save()

    @staticmethod
    def total_new_stat():
        pass
        stat = DSDailyStat.objects.values('created').annotate(total=Sum('total'), new=Sum('new')).order_by('created')
        for item in stat:
            # item['new'] = int(item['new'] / 1000)
            # item['total'] = int(item['total'] / 1000)
            try:
                item['percent'] = round(item['new'] / item['total'] * 100,2)
            except ZeroDivisionError:
                item['percent'] = 0
        for i in stat:
            print(i)
        return stat

class Settings(models.Model):
    name = models.CharField(
        primary_key=True,
        max_length=50,
        validators=[RegexValidator(regex='^[a-zA-Z_]+$')],
    )
    desc = models.CharField(max_length=255, blank=True)
    value = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Settings'
        verbose_name_plural = 'Settings'

    def __str__(self):
        return self.name

fb/remote_pc/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import DS, Settings, DSDailyStat
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required

def index(request):
    content = {

    }
    return render(request, 'remote_pc/index.html')
@login_required
def active(request):
    """Страница со статусами работы"""
    show_site_not_load_block_time =  Settings.objects.get(pk='show_site_not_load_block_time')
    main_page_reload_time = Settings.objects.get(pk='main_page_reload_time')
    dss = DS.objects.filter(use_in_pars=True)
    active_count = len(list(filter( lambda ds: ds.status['text'] == DS.WORK,dss)))
    is_not_word_exists = any(ds.status['text'] == DS.NOT_WORK for ds in dss)
    # active_count = 0
    # is_not_word_exists = False
    # for ds in dss:
    #     if ds.status()['text'] == DS.WORK:
    #         active_count += 1
    #     if ds.status()['text'] == DS.NOT_WORK:
    #         is_not_word_exists = True
    content = {
        'dss': dss,
        'show_site_not_load_block_time': show_site_not_load_block_time,
        'main_page_reload_time': main_page_reload_time,
        'active_count': active_count,
        'is_not_word_exists': is_not_word_exists,
    }
    return render(request, 'remote_pc/active.html', content)

def parse_stat(request):
    content = {
        'last_parse_date': DS.last_parse_date(),
        'daily_stat_total':  DS.daily_total_stat(),
        'dss_today_stat': DS.dss_today_stat(),
        'dss_avg_stat': DS.dss_avg_stat,
        'country_last_date_new_stat': DSDailyStat.country_last_date_new_stat(),
        'total_new_stat': DSDailyStat.total_new_stat(),
    }
    return render(request, 'remote_pc/parse_stat.html', content)
@require_http_methods(['GET'])
def ping_ds(request, ds_name):
    """Ручка для пропинговки дедиками"""
    try:
        ds = DS.objects.get(name=ds_name)
    except DS.DoesNotExist:
        return HttpResponse('Incorrect DS name', status=404)
    ds.ping()
    return HttpResponse('Ping success')

fb/remote_pc/templates/remote_pc/active.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  {% if is_not_word_exists%}
  <link rel="icon" type="image/x-icon" href="{% static 'red_circle.png' %}">
  {%endif%}
  <meta charset="UTF-8">
  <title>DS - {{active_count}}/{{dss|length}}</title>
  <meta http-equiv="refresh" content="{{main_page_reload_time.value}}" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<!--ICONS-->
<script src="https://kit.fontawesome.com/da43c2ea11.js" crossorigin="anonymous"></script>
  </head>
<style>
  #timeout{
    position: fixed;
    top: 20px;
    left: 20px;
    color: red;
    background-color: white;
    outline: 10px solid red;
    border-radius: 20px;
  }
  i{
    width: 20%;
    font-size: 15em;
  }
  .status{
  width: 100%;
  }
  .os i{
    font-size: 1.7em;
    margin-right: 5px;
  }
  .os{
    display: flex;
    align-items: center;
  }
  .fa-windows{
    color:#1f8ae8;
  }
  p {
  margin-bottom: 0rem;
}
.msg {
  margin: 0 10px;
  padding: 0;
  display: inline-block;
  background: rgb(21, 180, 21);
  box-shadow: 0 0 10px rgb(21, 180, 21);
  width: 15px;
  height: 15px;
  border-radius: 50%;
  animation-name: blink;
  animation-duration: .4s;
  animation-iteration-count: infinite;
  animation-direction: alternate;
  animation-timing-function: linear;
}

@keyframes blink {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

</style>
<style>

.server{
  width: 160px;
  height: 40px;
  background: #3a3a3a;
  border-radius: 1px;
}

.server ul{
  margin: 0;
  padding: 0;
  list-style: none;
}

.server ul li{
  width: 14px;
  height: 14px;
  float: left;
  margin-left: 12px;
  margin-top: 12px;
  background: rgba(149,244,118,0.6);
}


.server ul li:first-child{
  -webkit-animation: pattern1 0.14s linear infinite;
}

.server ul li:nth-child(2){
  -webkit-animation: pattern1 0.14s 0.02s linear infinite;
}
.server ul li:nth-child(3){
  -webkit-animation: pattern1 0.14s 0.035s linear infinite;
}

.server ul li:last-child{
  -webkit-animation: pattern1 0.14s 0.05s linear infinite;
}

@-webkit-keyframes pattern1{
  0%{
    background: rgba(149,244,118,0.6);
  }
  100%{
    background: rgba(149,244,118,1);
  }
}

.warning ul li{

  background: rgba(245,190,0,0.6);
}

.danger ul li{
  background: rgba(236,69,62,0.6);
}

.secondary ul li{
    background: rgba(129, 129, 129, 0.6);
}

.warning ul li:first-child{
  -webkit-animation: pattern2 0.14s linear infinite;
}

.warning ul li:nth-child(2){
  -webkit-animation: pattern2 0.14s 0.02s linear infinite;
}
.warning ul li:nth-child(3){
  -webkit-animation: pattern2 0.14s 0.035s linear infinite;
}

.warning ul li:last-child{
  -webkit-animation: pattern2 0.14s 0.05s linear infinite;
}

@-webkit-keyframes pattern2{
  0%{
    background: rgba(245,190,0,0.6);
  }
  100%{
    background: rgba(245,190,0,1);
  }
}



.danger ul li:first-child{
  -webkit-animation: pattern3 0.9s linear infinite;
}

.danger ul li:nth-child(2){
  -webkit-animation: pattern3 0.9s linear infinite;
}
.danger ul li:nth-child(3){
  -webkit-animation: pattern3 0.9s linear infinite;
}

.danger ul li:last-child{
  -webkit-animation: pattern3 0.9s linear infinite;
}

@-webkit-keyframes pattern3{
  0%{
    background: rgba(236,69,62,0.6);
  }
  80%{
    background: rgba(236,69,62,0.6);
  }
  100%{
    background: rgba(236,69,62,1);
  }
}
.secondary ul li:first-child{
  -webkit-animation: pattern4 0.9s linear infinite;
}

.secondary ul li:nth-child(2){
  -webkit-animation: pattern4 0.9s linear infinite;
}
.secondary ul li:nth-child(3){
  -webkit-animation: pattern4 0.9s linear infinite;
}

.secondary ul li:last-child{
  -webkit-animation: pattern4 0.9s linear infinite;
}


@-webkit-keyframes pattern4{
  0%{
    background: rgba(143, 143, 143, 0.6);
  }
  100%{
    background: rgba(143, 143, 143, 0.6);
  }
}
</style>
<body>
  <div class="" id="timeout" style="display: none;">
    <i class="fa-solid fa-rotate-right"></i>
  </div>
  <div class="container">
    <h4>Работет: {%if active_count%}<span class="msg"></span>{%endif%}{{active_count}}/{{dss|length}}</h4>
  </div>
  <div class="container">
    <table class="table align-middle">
      <thead class="table-primary">
        <tr>
          <th scope="col">IP</th>
          <th scope="col">OS</th>
          <th scope="col">Param</th>
                    <th scope="col">Name</th>
          <th scope="col">Status</th>
          <th scope="col">Last ping</th>
          <th scope="col">Past</th>
        </tr>
      </thead>
      <tbody>
        {%for ds in dss%}
        
        <tr>
          <td>
            <p>{{ds.login}}@{{ds.ip}}</p>
            <p>pass: {{ds.password}}</p>
          </td>
          <td >
            <div class="os">
              {% if ds.os == 'Linux'%}
              <i class="fa-brands fa-linux"></i>
              {% endif%}
              {% if ds.os == 'Windows'%}
              <i class="fa-brands fa-windows"></i>
              {% endif%}
            {{ds.os}}
            </div>
          </td>
          <td>{{ds.code}} {{ds.ram}}GB</td>
          <td>
            <h4>{{ds.name}}</h4>
          </td>
          <td>
            <div class="server {{ds.status.color}}">
              <ul>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
              </ul>
            </div>
            <!-- <button type="button" class="status btn btn-{{ds.status.color}}">{{ds.status.text}}</button> -->
          </td>
          <td>
            {{ds.last_activity|date:"m-d H:i:s"}}
          </td>
          <td>
            {{ds.past}}
          </td>
        </tr>
        
        {%endfor%}
      </tbody>
    </table>
  </div>
  <script>
    var timeOut = {{show_site_not_load_block_time.value}} * 1000
    setTimeout(function () {
      var elem = document.getElementById('timeout')
      elem.style.display = 'flex'
    }, timeOut);
  </script>
</body>

</html>

fb/remote_pc/templates/remote_pc/index.html
{%extends 'ads/base.html'%}

{%block head_text%}
DSs
{%endblock%}
{%block content%}


<style>
    .card i{
        font-size: 150px;
        text-align: center;
        margin: 10px 0;
        color: rgb(58 108 224);
    }
</style>
<br>
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
          <div class="card text-center">
            <a href="{%url 'remote_pc:active' %}">
                <i class="fa-solid fa-signal"></i>
            </a>
            <div class="card-body">
              <h5 class="card-title">Актиные</h5>
              <p class="card-text">Активные парс-машины</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card text-center">
            <a href="{%url 'remote_pc:parse_stat' %}">
                <i class="fa-solid fa-chart-column"></i>
            </a>
            <div class="card-body">
              <h5 class="card-title">Статистика</h5>
              <p class="card-text">Статистика парсинга</p>
            </div>
          </div>
        </div>
      </div>
</div>
{%endblock%}

fb/remote_pc/templates/remote_pc/parse_stat.html
{%extends 'ads/base.html'%}

{%block head_text%}
Статистика парсинга
{%endblock%}
{%block content%}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<div class="container-fluid">

  <div class="row">
    <div class="col-6">
      <canvas id="dss_avg_stat"></canvas>
    </div>
    <div class="col-6">
      <canvas id="dss_today_stat"></canvas>


    </div>
  </div>
</div>
<div class="container-fluid">
  <!-- Статистика новых по странам за последний день -->
  <div class="row">
    <div class="col">
      <canvas id="daily_stat_total"></canvas>
    </div>
    <div class="col">
      <canvas id="country_last_date_new_stat"></canvas>
    </div>
  </div>
</div>
<div class="container">
  <canvas id="total-new"></canvas>
</div>


<script>
  //dss_avg_stat
  const dss_avg_stat = document.getElementById('dss_avg_stat');
  const dss_avg_stat_labels = [
    // {%for item in dss_avg_stat%}
    '{{item.ds__prefix}}{{item.ds__number}}',
    // {%endfor%}
  ];
  const dss_avg_stat_data = {
    labels: dss_avg_stat_labels,
    datasets: [{
      label: 'Статистика спаршеных карточек по парсерам за все время',
      data: [
        // {%for item in dss_avg_stat%}
        '{{item.avg}}',
        // {%endfor%}
      ],
      backgroundColor:
        [
          // {%for item in dss_avg_stat%}
          '{{item.ds__color}}',
          // {%endfor%}
        ],
      borderWidth: 1
    }]
  };


  const dss_avg_stat_config = {
    type: 'bar',
    data: dss_avg_stat_data,
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
      }
    },
  };


  new Chart(dss_avg_stat, dss_avg_stat_config)
</script>


<script>
  //dss_today_stat
  const dss_today_stat = document.getElementById('dss_today_stat');
  const dss_today_stat_labels = [
    // {%for item in dss_today_stat%}
    '{{item.ds__prefix}}{{item.ds__number}}',
    // {%endfor%}
  ];
  const dss_today_stat_data = {
    labels: dss_today_stat_labels,
    datasets: [{
      label: 'Статистика спаршеных карточек по парсерам за {{last_parse_date}}',
      data: [
        // {%for item in dss_today_stat%}
        '{{item.avg}}',
        // {%endfor%}
      ],
      backgroundColor:
        [
          // {%for item in dss_today_stat%}
          '{{item.ds__color}}',
          // {%endfor%}
        ],
      borderWidth: 1
    }]
  };


  const dss_today_stat_config = {
    type: 'bar',
    data: dss_today_stat_data,
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
      }
    },
  };


  new Chart(dss_today_stat, dss_today_stat_config)
</script>
<script>
  //daily_stat_total
  const daily_stat_total = document.getElementById('daily_stat_total');
  const labels = [
    // {%for item in daily_stat_total%}
    '{{item.created}}',
    // {%endfor%}
  ];
  const data = {
    labels: labels,
    datasets: [{
      label: 'Статистика спаршеных карточек по дням',
      data: [
        // {%for item in daily_stat_total%}
        '{{item.total}}',
        // {%endfor%}
      ],
      borderWidth: 1
    }]
  };


  const config = {
    type: 'bar',
    data: data,
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
      }
    },
  };


  new Chart(daily_stat_total, config)
</script>

<script>
  //Статистика новых по странам за последний день
  const country_last_date_new_stat = document.getElementById('country_last_date_new_stat');
  const country_last_date_new_stat_labels = [
    // {%for item in country_last_date_new_stat.stat%}
    '{{item.country_id|upper}} {{item.avg}}%',
    // {%endfor%}
  ];
  const country_last_date_new_stat_data = {
    labels: country_last_date_new_stat_labels,
    datasets: [

      {
        label: 'Новых групп',
        data: [
          // {%for item in country_last_date_new_stat.stat%}
          '{{item.new}}',
          // {%endfor%}
        ],

      },
      {
        label: 'Всего карт',
        data: [
          // {%for item in country_last_date_new_stat.stat%}
          '{{item.total}}' - '{{item.new}}',
          // {%endfor%}
        ],

      },
    ]
  };


  const country_last_date_new_stat_config = {
    type: 'bar',
    data: country_last_date_new_stat_data,
    options: {
      scales: {
        x: {
          stacked: true,
        },
        y: {
          stacked: true
        }
      }
    },
  };
  new Chart(country_last_date_new_stat, country_last_date_new_stat_config)
</script>
<script>
  // TOTAL-NEW
  const DATA_COUNT = {{total_new_stat|length}};
  const TotalNewLabels = [
      // {%for item in total_new_stat%}
      '{{item.created}}',
          // {%endfor%}
  ];
  // for (let i = 0; i < DATA_COUNT; ++i) {
  //   TotalNewLabels.push(i.toString());
  // }

  const TotalNewData = {
    labels: TotalNewLabels,
    datasets: [
      {
        label: 'Total',
        data: [
          // {%for item in total_new_stat%}
          '{{item.percent}}',
          // {%endfor%}
        ],
        borderColor: '#a72b2b',
        fill: false,
        cubicInterpolationMode: 'monotone',
        tension: 0.4
      }, 
      // {
      //   label: 'New',
      //   data: [
      //     // {%for item in total_new_stat%}
      //     '{{item.new}}',
      //     // {%endfor%}
      //   ],
      //   borderColor: '#2ba769',
      //   fill: false,
      //   tension: 0.4
      // },
    ]
  };

  const TotalNewConfig = {
    type: 'line',
    data: TotalNewData,
    options: {
      responsive: true,
      plugins: {
        title: {
          display: true,
          text: 'Соотношение карточек к новым группам в %'
        },
      },
      interaction: {
        intersect: false,
      },
      scales: {
        x: {
          display: true,
          title: {
            display: true
          }
        },
        y: {
          display: true,
          title: {
            display: true,
            text: 'Value'
          },
          suggestedMin: 0,
          suggestedMax: 10
        }
      }
    },
  };

  const totalNewStat = document.getElementById('total-new');
  new Chart(totalNewStat, TotalNewConfig)
</script>

{%endblock%}